name: Lint

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install and cache dependencies
        uses: bahmutov/npm-install@v1

      - name: Run linter
        run: npm run lint
